#pragma once
#define PERMISSIVE_HOLD
#undef IGNORE_MOD_TAP_INTERRUPT

#undef MOUSEKEY_DELAY
#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_MAX_SPEED

#define MOUSEKEY_DELAY          50
#define MOUSEKEY_INTERVAL       20
#define MOUSEKEY_TIME_TO_MAX    30
#define MOUSEKEY_MAX_SPEED      8

#define MOUSEKEY_WHEEL_MAX_SPEED 5